### ISSUE TITLE
Figure out an alternative to `siphash`

### ISSUE THREAD

**Issue by RyanGlScott** [ekmett/hyperloglog#30]
`hyperloglog` depends on [`siphash`](https://hackage.haskell.org/package/siphash), which has been deprecated. This presents issues for building `hyperloglog` with GHC 9.2.1, as `siphash` fails to build with 9.2.1:

```
[1 of 1] Compiling Crypto.MAC.SipHash ( Crypto/MAC/SipHash.hs, dist/build/Crypto/MAC/SipHash.o, dist/build/Crypto/MAC/SipHash.dyn_o )

Crypto/MAC/SipHash.hs:46:33: error:
    Variable not in scope: inlinePerformIO :: IO SipHash -> SipHash
   |
46 | hashWith c d key (PS ps s fl) = inlinePerformIO $ withForeignPtr ps (\ptr -> runHash (initSip key) (ptr `plusPtr` s) fl)
   |                                 ^^^^^^^^^^^^^^^
```

**Comment by cartazio** [comment]
So we need to internalize it or put a sip hash in say the hash package?

**Comment by cartazio** [comment]
Internalizing the code might be the simplest approach. Though factoring it
out has other tradeoffs

**Comment by RyanGlScott** [comment]
Yes, it seems like we'll need to figure out some other place to reach for this code. The package which replaced `siphash` is [`memory`](https://hackage.haskell.org/package/memory), but it contains much, much more than just siphash. I wouldn't be opposed to putting a copy of the code in another package, or even internalizing it.

**Comment by cartazio** [comment]
hrm, the code looks pretty self contained and small 

https://github.com/vincenthz/hs-siphash/blob/b0e6d919db02cf8be1a16df4a81745c0df3a2d6b/Crypto/MAC/SipHash.hs#L30-L159

though it also looks like the sortah code that ghc isn't exactly the best at optimizing, though this style impl does mean it should be working on non-nativecode ghc backends (such as they are)

**Comment by RyanGlScott** [comment]
For now, I've opted to go with the internalization route. See #31.
